# Generated by Django 3.2.8 on 2021-11-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.BooleanField(choices=[('tipo6', 'MKV'), ('tipo7', 'FLV'), ('tipo3', 'WMV'), ('tipo5', 'H.264'), ('tipo4', '.MOV'), ('tipo1', 'AVI'), ('tipo2', 'MPG')], verbose_name='Elegir formato contenedor')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Duración')),
            ],
        ),
    ]
