# Generated by Django 3.2.8 on 2021-11-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0002_format_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the movie')),
                ('synthesis', models.TextField(max_length=100, verbose_name='Movie Synthesis')),
                ('director', models.CharField(max_length=50, verbose_name='Directed by')),
                ('protagonist', models.CharField(max_length=50, verbose_name='Protagonists')),
                ('picture', models.ImageField(upload_to='Insert Picture')),
                ('rating', models.CharField(max_length=3, verbose_name='Movie rating')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Movie length')),
                ('format', models.BooleanField(choices=[('1', 'AVI'), ('2', 'MPG'), ('3', 'WMV'), ('4', '.MOV'), ('5', 'H.264'), ('6', 'MKV'), ('7', 'FLV')], verbose_name='Choose container format')),
            ],
        ),
        migrations.DeleteModel(
            name='Format',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.TextField(default='Container', max_length=1000, verbose_name='Add reply to comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Do you like the comment?'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='insert',
            field=models.TextField(max_length=1000, verbose_name='Add Comment'),
        ),
        migrations.AlterField(
            model_name='score',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Do you liked the movie?'),
        ),
    ]
